package com.arkonas.ranks.menu;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.function.Supplier;
import net.kyori.adventure.text.Component;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.entity.Player;
import com.arkonas.ranks.ranks.Rank;

/**
 * Hand-written per-rank menu lore, authored in {@code rankups.yml} /
 * {@code prestiges.yml} rather than generated by the plugin:
 *
 * <pre>
 * Aexample:
 *   rank: 'A'
 *   next: 'B'
 *   requirements:
 *     - 'money 5000'
 *   lore:
 *     - '&amp;e&amp;lREQUIREMENTS'
 *     - '{requirements}'
 *     - ''
 *     - '&amp;7Unlocks the &amp;f{{next.rank}} &amp;7mine'
 * </pre>
 *
 * <p>When a rank declares lore it <em>replaces</em> the generated lines on that
 * item; the {@code {requirements}} token puts the generated requirement block back
 * wherever the author wants it. {@code {rewards}} expands to the rank's rewards
 * block on the confirmation panel. Everything else goes through the normal
 * Pebble/PlaceholderAPI pipeline, so {@code {{rank.rank}}}, {@code {{next.rank}}},
 * colour codes and MiniMessage tags all work.
 *
 * <p>The base {@code lore} key applies to every screen; {@code lore-current},
 * {@code lore-locked}, {@code lore-complete} (rank path / prestige list item states)
 * and {@code lore-info} (the confirmation screen's info panel) override it on that
 * screen alone.
 */
public class RankLore {

  /** The rank the player is standing on, in the rank path / prestige list. */
  public static final String CURRENT = "current";
  /** A rank the player has not reached yet. */
  public static final String LOCKED = "locked";
  /** A rank the player has already passed. */
  public static final String COMPLETE = "complete";
  /** The info panel at slot 13 of the rankup/prestige confirmation screen. */
  public static final String INFO = "info";

  private static final String REQUIREMENTS_TOKEN = "{requirements}";

  private final MenuModule module;

  public RankLore(MenuModule module) {
    this.module = module;
  }

  /** True when this rank hand-writes the lore for {@code variant}. */
  public boolean has(Rank rank, String variant) {
    return raw(rank, variant) != null;
  }

  /**
   * The raw lore lines for a rank: {@code lore-<variant>} wins, then the base
   * {@code lore} key, then null when the rank declares neither.
   */
  public List<String> raw(Rank rank, String variant) {
    ConfigurationSection section = rank == null ? null : rank.getSection();
    if (section == null) {
      return null;
    }
    List<String> variantLines = variant == null ? null : lines(section, "lore-" + variant);
    return variantLines != null ? variantLines : lines(section, "lore");
  }

  /** One lore key off a section: a list of lines, a single string, or null when unset/empty. */
  private static List<String> lines(ConfigurationSection section, String key) {
    if (section.isList(key)) {
      List<String> list = section.getStringList(key);
      return list.isEmpty() ? null : list;
    }
    String single = section.getString(key);
    return single == null || single.isEmpty() ? null : List.of(single);
  }

  /**
   * Renders a rank's hand-written lore, or null when it has none (callers then
   * fall back to the generated lore they built before).
   *
   * @param requirements supplies the generated requirement block, invoked only when
   *     the author actually used {@code {requirements}}
   * @param rewards the rewards block substituted into {@code {rewards}}, or null
   */
  public List<Component> render(Player player, Rank rank, Rank next, String variant,
      Supplier<List<Component>> requirements, String rewards) {
    List<String> raw = raw(rank, variant);
    if (raw == null) {
      return null;
    }
    String joined = String.join("\n", raw);
    if (rewards != null) {
      joined = MenuText.sub(joined, Map.of("rewards", rewards));
    }

    MenuText text = module.getText();
    List<Component> lore = new ArrayList<>();
    List<Component> requirementBlock = null;
    for (String line : joined.split("\n", -1)) {
      if (line.trim().equals(REQUIREMENTS_TOKEN)) {
        if (requirements != null) {
          if (requirementBlock == null) {
            requirementBlock = requirements.get();
          }
          lore.addAll(requirementBlock);
        }
        continue;
      }
      lore.add(text.component(player, line, rank, next));
    }
    return lore;
  }

  /**
   * The rank's rewards block, i.e. what {@code {rewards}} expands to: its own
   * {@code <menu>.rewards} or bare {@code rewards} key, else the locale
   * {@code rewards-default}.
   *
   * @param menuKey {@code rankup} or {@code prestige}
   */
  public String rewards(Rank rank, String menuKey) {
    ConfigurationSection section = rank == null ? null : rank.getSection();
    if (section != null) {
      String override = firstNonBlank(
          section.getString(menuKey + ".rewards"),
          section.getString("rewards"));
      if (override != null) {
        return override;
      }
    }
    return module.getText().raw(menuKey + ".rewards-default",
        "&8• &7Unlocks the &f{{next.rank}} &7rank");
  }

  private static String firstNonBlank(String... values) {
    for (String value : values) {
      if (value != null && !value.isBlank()) {
        return value;
      }
    }
    return null;
  }

  /**
   * The generated requirement block, i.e. what {@code {requirements}} expands to. Every line
   * comes from the {@code menu.requirements} templates — see {@link RequirementLore}.
   */
  public List<Component> requirementLines(Player player, Rank rank, boolean showProgress) {
    return requirementLines(player, rank, null, showProgress);
  }

  /** The requirement block, with {@code next} bound for {@code {{next.rank}}} in a template. */
  public List<Component> requirementLines(Player player, Rank rank, Rank next,
      boolean showProgress) {
    return module.getRequirementLore().render(player, rank, next, showProgress);
  }

  /**
   * The requirement block reduced to what the player has <em>not</em> finished yet, for the
   * locked action button on the confirmation screen.
   */
  public List<Component> unmetRequirementLines(Player player, Rank rank, Rank next) {
    return module.getRequirementLore().render(player, rank, next, true, true);
  }
}
